package com.witcher.downloadmanlib.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.witcher.downloadmanlib.entity.Range;
import com.witcher.downloadmanlib.entity.DownloadMission;

import com.witcher.downloadmanlib.db.RangeDao;
import com.witcher.downloadmanlib.db.DownloadMissionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig rangeDaoConfig;
    private final DaoConfig downloadMissionDaoConfig;

    private final RangeDao rangeDao;
    private final DownloadMissionDao downloadMissionDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        rangeDaoConfig = daoConfigMap.get(RangeDao.class).clone();
        rangeDaoConfig.initIdentityScope(type);

        downloadMissionDaoConfig = daoConfigMap.get(DownloadMissionDao.class).clone();
        downloadMissionDaoConfig.initIdentityScope(type);

        rangeDao = new RangeDao(rangeDaoConfig, this);
        downloadMissionDao = new DownloadMissionDao(downloadMissionDaoConfig, this);

        registerDao(Range.class, rangeDao);
        registerDao(DownloadMission.class, downloadMissionDao);
    }
    
    public void clear() {
        rangeDaoConfig.clearIdentityScope();
        downloadMissionDaoConfig.clearIdentityScope();
    }

    public RangeDao getRangeDao() {
        return rangeDao;
    }

    public DownloadMissionDao getDownloadMissionDao() {
        return downloadMissionDao;
    }

}
